package ce.jku.at.rdfwriter;
 
/* CVS $Id: $ */

import org.apache.jena.rdf.model.*;

/**
 * Vocabulary definitions from standard-pass-ont-ingolstadt-rebuild.owl
 * @author Auto-generated by schemagen on 10 Jun 2017 15:29
 * 
 * Generated via command prompt with following inputs:
 * c:\>set jenaroot=C:\Users\Max Silber\Downloads\apache-jena-3.3.0\apache-jena-3.3.0
 * c:\>set path=%path%;%jenaroot%\bat
 * c:\>schemagen.bat -i standard-pass-ont-ingolstadt-rebuild.owl -a http://www.i2pm.net/standard-pass-ont# --owl
 * 
 */
public class PassOntology {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static final Model M_MODEL = ModelFactory.createDefaultModel();

    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://www.i2pm.net/standard-pass-ont#";

    /** <p>The namespace of the vocabulary as a string</p>
     * @return namespace as String
     * @see #NS */
    public static String getURI() {return NS;}

    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = M_MODEL.createResource( NS );

    public static final Property PASSModelDataPropertie = M_MODEL.createProperty( "http://www.i2pm.net/standard-pass-ont#PASSModelDataPropertie" );

    public static final Property belongsTo = M_MODEL.createProperty( "http://www.i2pm.net/standard-pass-ont#belongsTo" );

    public static final Property contains = M_MODEL.createProperty( "http://www.i2pm.net/standard-pass-ont#contains" );

    public static final Property containsBaseBehavior = M_MODEL.createProperty( "http://www.i2pm.net/standard-pass-ont#containsBaseBehavior" );

    public static final Property containsBehavior = M_MODEL.createProperty( "http://www.i2pm.net/standard-pass-ont#containsBehavior" );

    public static final Property containsPayloadDescription = M_MODEL.createProperty( "http://www.i2pm.net/standard-pass-ont#containsPayloadDescription" );

    public static final Property guardedBy = M_MODEL.createProperty( "http://www.i2pm.net/standard-pass-ont#guardedBy" );

    public static final Property guardsState = M_MODEL.createProperty( "http://www.i2pm.net/standard-pass-ont#guardsState" );

    public static final Property hasAdditionalAttribute = M_MODEL.createProperty( "http://www.i2pm.net/standard-pass-ont#hasAdditionalAttribute" );

    public static final Property hasBusinessDayDurationTimeOutTime = M_MODEL.createProperty( "http://www.i2pm.net/standard-pass-ont#hasBusinessDayDurationTimeOutTime" );

    public static final Property hasCalendarBasedReoccuranceTimeOutTime = M_MODEL.createProperty( "http://www.i2pm.net/standard-pass-ont#hasCalendarBasedReoccuranceTimeOutTime" );

    public static final Property hasDataDefinition = M_MODEL.createProperty( "http://www.i2pm.net/standard-pass-ont#hasDataDefinition" );

    public static final Property hasDataMapping = M_MODEL.createProperty( "http://www.i2pm.net/standard-pass-ont#hasDataMapping" );

    public static final Property hasDataMappingString = M_MODEL.createProperty( "http://www.i2pm.net/standard-pass-ont#hasDataMappingString" );

    public static final Property hasDataType = M_MODEL.createProperty( "http://www.i2pm.net/standard-pass-ont#hasDataType" );

    public static final Property hasDayTimeDurationTimeOutTime = M_MODEL.createProperty( "http://www.i2pm.net/standard-pass-ont#hasDayTimeDurationTimeOutTime" );

    public static final Property hasDurationTimeOutTime = M_MODEL.createProperty( "http://www.i2pm.net/standard-pass-ont#hasDurationTimeOutTime" );

    public static final Property hasEndState = M_MODEL.createProperty( "http://www.i2pm.net/standard-pass-ont#hasEndState" );

    public static final Property hasFunctionSpecification = M_MODEL.createProperty( "http://www.i2pm.net/standard-pass-ont#hasFunctionSpecification" );

    public static final Property hasHandlingStrategy = M_MODEL.createProperty( "http://www.i2pm.net/standard-pass-ont#hasHandlingStrategy" );

    public static final Property hasIncomingMessageExchange = M_MODEL.createProperty( "http://www.i2pm.net/standard-pass-ont#hasIncomingMessageExchange" );

    public static final Property hasIncomingTransition = M_MODEL.createProperty( "http://www.i2pm.net/standard-pass-ont#hasIncomingTransition" );

    public static final Property hasInitialState = M_MODEL.createProperty( "http://www.i2pm.net/standard-pass-ont#hasInitialState" );

    public static final Property hasInputPoolConstraint = M_MODEL.createProperty( "http://www.i2pm.net/standard-pass-ont#hasInputPoolConstraint" );

    public static final Property hasKey = M_MODEL.createProperty( "http://www.i2pm.net/standard-pass-ont#hasKey" );

    public static final Property hasKeyValuePair = M_MODEL.createProperty( "http://www.i2pm.net/standard-pass-ont#hasKeyValuePair" );

    public static final Property hasLimit = M_MODEL.createProperty( "http://www.i2pm.net/standard-pass-ont#hasLimit" );

    public static final Property hasMaximumSubjectInstanceRestriction = M_MODEL.createProperty( "http://www.i2pm.net/standard-pass-ont#hasMaximumSubjectInstanceRestriction" );

    public static final Property hasMessageExchange = M_MODEL.createProperty( "http://www.i2pm.net/standard-pass-ont#hasMessageExchange" );

    public static final Property hasMessageType = M_MODEL.createProperty( "http://www.i2pm.net/standard-pass-ont#hasMessageType" );

    public static final Property hasMetaData = M_MODEL.createProperty( "http://www.i2pm.net/standard-pass-ont#hasMetaData" );

    /** <p>should be unique</p> */
    public static final Property hasModelComponentID = M_MODEL.createProperty( "http://www.i2pm.net/standard-pass-ont#hasModelComponentID" );

    public static final Property hasModelComponentLable = M_MODEL.createProperty( "http://www.i2pm.net/standard-pass-ont#hasModelComponentLable" );

    public static final Property hasOutgoingMessageExchange = M_MODEL.createProperty( "http://www.i2pm.net/standard-pass-ont#hasOutgoingMessageExchange" );

    public static final Property hasOutgoingTransition = M_MODEL.createProperty( "http://www.i2pm.net/standard-pass-ont#hasOutgoingTransition" );

    public static final Property hasPriorityNumber = M_MODEL.createProperty( "http://www.i2pm.net/standard-pass-ont#hasPriorityNumber" );

    public static final Property hasReceiver = M_MODEL.createProperty( "http://www.i2pm.net/standard-pass-ont#hasReceiver" );

    public static final Property hasRelationToModelComponent = M_MODEL.createProperty( "http://www.i2pm.net/standard-pass-ont#hasRelationToModelComponent" );

    /** <p>inAccordance witht the classes ReoccuranceTimeOutTransition and ReoccuranceTimeOutExitCondition
     *  Strings of this datatype are not formally defined and are likely to be more
     *  complex</p>
     */
    public static final Property hasReoccuranceTimeOutTime = M_MODEL.createProperty( "http://www.i2pm.net/standard-pass-ont#hasReoccuranceTimeOutTime" );

    public static final Property hasSender = M_MODEL.createProperty( "http://www.i2pm.net/standard-pass-ont#hasSender" );

    public static final Property hasSourceState = M_MODEL.createProperty( "http://www.i2pm.net/standard-pass-ont#hasSourceState" );

    public static final Property hasStartSubject = M_MODEL.createProperty( "http://www.i2pm.net/standard-pass-ont#hasStartSubject" );

    public static final Property hasTargetState = M_MODEL.createProperty( "http://www.i2pm.net/standard-pass-ont#hasTargetState" );

    public static final Property hasTimeBasedReoccuranceTimeOutTime = M_MODEL.createProperty( "http://www.i2pm.net/standard-pass-ont#hasTimeBasedReoccuranceTimeOutTime" );

    public static final Property hasTimeoutValue = M_MODEL.createProperty( "http://www.i2pm.net/standard-pass-ont#hasTimeoutValue" );

    public static final Property hasToolSpecificDefinition = M_MODEL.createProperty( "http://www.i2pm.net/standard-pass-ont#hasToolSpecificDefinition" );

    public static final Property hasTransitionCondition = M_MODEL.createProperty( "http://www.i2pm.net/standard-pass-ont#hasTransitionCondition" );

    public static final Property hasValue = M_MODEL.createProperty( "http://www.i2pm.net/standard-pass-ont#hasValue" );

    public static final Property hasYearMonthDurationTimeOutTime = M_MODEL.createProperty( "http://www.i2pm.net/standard-pass-ont#hasYearMonthDurationTimeOutTime" );

    public static final Property isBaseBehaviorOf = M_MODEL.createProperty( "http://www.i2pm.net/standard-pass-ont#isBaseBehaviorOf" );

    public static final Property isContainedIn = M_MODEL.createProperty( "http://www.i2pm.net/standard-pass-ont#isContainedIn" );

    public static final Property isEndStateOf = M_MODEL.createProperty( "http://www.i2pm.net/standard-pass-ont#isEndStateOf" );

    public static final Property isInitialStateOf = M_MODEL.createProperty( "http://www.i2pm.net/standard-pass-ont#isInitialStateOf" );

    public static final Property isOptionalToEndChoiceSegmentPath = M_MODEL.createProperty( "http://www.i2pm.net/standard-pass-ont#isOptionalToEndChoiceSegmentPath" );

    public static final Property isOptionalToStartChoiceSegmentPath = M_MODEL.createProperty( "http://www.i2pm.net/standard-pass-ont#isOptionalToStartChoiceSegmentPath" );

    public static final Property referencesMacroBehavior = M_MODEL.createProperty( "http://www.i2pm.net/standard-pass-ont#referencesMacroBehavior" );

    public static final Property requiresPerformedMessageExchange = M_MODEL.createProperty( "http://www.i2pm.net/standard-pass-ont#requiresPerformedMessageExchange" );

    public static final Resource Action = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#Action" );

    public static final Resource AdditionalAttribute = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#AdditionalAttribute" );

    public static final Resource BehaviorDescribingComponent = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#BehaviorDescribingComponent" );

    public static final Resource BusinessDayDurationExpiredTimeOutTransitionCondition = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#BusinessDayDurationExpiredTimeOutTransitionCondition" );

    public static final Resource BusinessDayTimeDurationTimeOutTransition = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#BusinessDayTimeDurationTimeOutTransition" );

    public static final Resource CalendarBasedReoccuranceTimeOutTransition = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#CalendarBasedReoccuranceTimeOutTransition" );

    public static final Resource CalendarBasedReoccuranceTimeOutTransitionCondition = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#CalendarBasedReoccuranceTimeOutTransitionCondition" );

    public static final Resource ChoiceSegment = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#ChoiceSegment" );

    public static final Resource ChoiceSegmentPath = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#ChoiceSegmentPath" );

    public static final Resource CommunicationAct = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#CommunicationAct" );

    public static final Resource CommunicationTransition = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#CommunicationTransition" );

    public static final Resource CustomOrExternalDataTypeDefinition = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#CustomOrExternalDataTypeDefinition" );

    public static final Resource DataDescribingComponent = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#DataDescribingComponent" );

    public static final Resource DataMappingFunction = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#DataMappingFunction" );

    public static final Resource DataMappingIncommingToLocal = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#DataMappingIncommingToLocal" );

    public static final Resource DataMappingLocalToOutgoing = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#DataMappingLocalToOutgoing" );

    public static final Resource DataObjectDefinition = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#DataObjectDefinition" );

    public static final Resource DataObjectListDefintion = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#DataObjectListDefintion" );

    public static final Resource DataTypeDefinition = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#DataTypeDefinition" );

    /** <p>A condition that is true if a certain time defined in Days or hours, minuets,
     *  seconds or fractions of seconds, has passed since the state this condition
     *  belongs to has been entered.</p>
     */
    public static final Resource DayTimeDurationExpiredTimeOutTransitionCondition = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#DayTimeDurationExpiredTimeOutTransitionCondition" );

    public static final Resource DayTimeDurationTimeOutTransition = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#DayTimeDurationTimeOutTransition" );

    public static final Resource DoFunction = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#DoFunction" );

    public static final Resource DoState = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#DoState" );

    public static final Resource DoTransition = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#DoTransition" );

    public static final Resource DoTransitionCondition = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#DoTransitionCondition" );

    public static final Resource DurationExpiredTimeOutTransition = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#DurationExpiredTimeOutTransition" );

    /** <p>A condition that is true if a certain time defined has passed since the state
     *  this condition belongs to has been entered. (This is the standard TimeOut
     *  Exit condition)</p>
     */
    public static final Resource DurationExpiredTimeOutTransitionCondition = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#DurationExpiredTimeOutTransitionCondition" );

    public static final Resource EndState = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#EndState" );

    public static final Resource ErrorTransition = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#ErrorTransition" );

    public static final Resource FullySpecifiedSubject = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#FullySpecifiedSubject" );

    public static final Resource FunctionSpecification = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#FunctionSpecification" );

    public static final Resource GuardBehavior = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#GuardBehavior" );

    public static final Resource InitialStateOfBehavior = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#InitialStateOfBehavior" );

    public static final Resource InitialStateOfChoiceSegmentPath = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#InitialStateOfChoiceSegmentPath" );

    public static final Resource InputPoolConstraint = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#InputPoolConstraint" );

    public static final Resource InputPoolContstraintHandlingStrategy = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#InputPoolContstraintHandlingStrategy" );

    public static final Resource InteractionDescribingComponent = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#InteractionDescribingComponent" );

    public static final Resource InterfaceSubject = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#InterfaceSubject" );

    public static final Resource JSONDataTypeDefinition = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#JSONDataTypeDefinition" );

    public static final Resource KeyValuePair = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#KeyValuePair" );

    public static final Resource MacroBehavior = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#MacroBehavior" );

    public static final Resource MacroState = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#MacroState" );

    public static final Resource MandatoryToEndChoiceSegmentPath = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#MandatoryToEndChoiceSegmentPath" );

    public static final Resource MandatoryToStartChoiceSegmentPath = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#MandatoryToStartChoiceSegmentPath" );

    public static final Resource MessageExchange = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#MessageExchange" );

    public static final Resource MessageExchangeCondition = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#MessageExchangeCondition" );

    public static final Resource MessageExchangeList = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#MessageExchangeList" );

    public static final Resource MessageSenderTypeConstraint = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#MessageSenderTypeConstraint" );

    public static final Resource MessageSpecification = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#MessageSpecification" );

    public static final Resource MessageTypeConstraint = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#MessageTypeConstraint" );

    public static final Resource ModelBuiltInDataTypes = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#ModelBuiltInDataTypes" );

    public static final Resource MultiSubject = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#MultiSubject" );

    public static final Resource OWLDataTypeDefinition = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#OWLDataTypeDefinition" );

    public static final Resource OptionalToEndChoiceSegmentPath = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#OptionalToEndChoiceSegmentPath" );

    /** <p>ChoiceSegmentPath and (isOptionalToEndChoiceSegmentPath value false)</p> */
    public static final Resource OptionalToStartChoiceSegmentPath = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#OptionalToStartChoiceSegmentPath" );

    public static final Resource PASSProcessModel = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#PASSProcessModel" );

    public static final Resource PASSProcessModelElement = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#PASSProcessModelElement" );

    public static final Resource PayloadDataObjectDesfinition = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#PayloadDataObjectDesfinition" );

    public static final Resource PayloadDescription = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#PayloadDescription" );

    public static final Resource PhysicalObjectDescription = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#PhysicalObjectDescription" );

    public static final Resource ReceiveFunction = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#ReceiveFunction" );

    public static final Resource ReceiveState = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#ReceiveState" );

    public static final Resource ReceiveTransition = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#ReceiveTransition" );

    public static final Resource ReceiveTransitionCondition = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#ReceiveTransitionCondition" );

    /** <p>An transition (exit) condition that becomes true if a certain time since a
     *  previous trigger was set has passed. The condition may be defined as frequency
     *  over a given intervall. --&gt; eg 12x a year</p>
     */
    public static final Resource ReoccuranceEventTimeOutTransitionCondition = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#ReoccuranceEventTimeOutTransitionCondition" );

    public static final Resource ReoccuranceTimeOutTransition = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#ReoccuranceTimeOutTransition" );

    public static final Resource SendFunction = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#SendFunction" );

    public static final Resource SendState = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#SendState" );

    public static final Resource SendTransition = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#SendTransition" );

    public static final Resource SendTransitionCondition = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#SendTransitionCondition" );

    public static final Resource SenderTypeConstraint = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#SenderTypeConstraint" );

    public static final Resource SingleSubject = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#SingleSubject" );

    public static final Resource StandardPASSState = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#StandardPASSState" );

    public static final Resource StartSubject = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#StartSubject" );

    public static final Resource State = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#State" );

    public static final Resource Subject = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#Subject" );

    public static final Resource SubjectBaseBehavior = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#SubjectBaseBehavior" );

    public static final Resource SubjectBehavior = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#SubjectBehavior" );

    public static final Resource SubjectDataDefinition = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#SubjectDataDefinition" );

    public static final Resource TimeBasedReoccuranceTimeOutTransitionCondition = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#TimeBasedReoccuranceTimeOutTransitionCondition" );

    public static final Resource TimeBasedReocurranceTimeOutTransition = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#TimeBasedReocurranceTimeOutTransition" );

    public static final Resource TimeOutTransition = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#TimeOutTransition" );

    /** <p>a condition that is deemed 'true' and thus the according edge is gone, if:
     *  a surrounding execution system has deemed the time since entering the state
     *  and starting with the execution of the according action as too long (predefined
     *  by the outgoing edge)</p>
     */
    public static final Resource TimeOutTransitionCondition = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#TimeOutTransitionCondition" );

    public static final Resource Transition = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#Transition" );

    public static final Resource TransitionCondition = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#TransitionCondition" );

    public static final Resource UserCancelTransition = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#UserCancelTransition" );

    public static final Resource XSD_DataTypeDefinition = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#XSD-DataTypeDefinition" );

    public static final Resource YearMonthDurationExpiredTimeOutTransitionCondition = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#YearMonthDurationExpiredTimeOutTransitionCondition" );

    public static final Resource YearMonthDurationTimeOutTransition = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#YearMonthDurationTimeOutTransition" );

    public static final Resource DefaultFunctionDo = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#DefaultFunctionDo" );

    public static final Resource DefaultFunctionReceive = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#DefaultFunctionReceive" );

    public static final Resource DefaultFunctionSend = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#DefaultFunctionSend" );

    public static final Resource InputPoolConstraintStrategy_Blocking = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#InputPoolConstraintStrategy-Blocking" );

    public static final Resource InputPoolConstraintStrategy_DeleteLatest = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#InputPoolConstraintStrategy-DeleteLatest" );

    public static final Resource InputPoolConstraintStrategy_DeleteOldest = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#InputPoolConstraintStrategy-DeleteOldest" );

    public static final Resource InputPoolConstraintStrategy_Drop = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#InputPoolConstraintStrategy-Drop" );

    /** <p>This datatype is derived from xsd:dayTimeDuration and denotes that the specified
     *  interval is not meant in standard calendarial days(24h) but rather official
     *  business days Be aware that for formal evaluation it would be necessary to
     *  determin the business location this duration is referencing (e.g. a business
     *  day in France may be a holiday in Germany and vice versa)</p>
     */
    public static final Resource businessDayTimeDuration = M_MODEL.createResource( "http://www.i2pm.net/standard-pass-ont#businessDayTimeDuration" );

}